package br.univille.ShrinersSantaCatarinaSystem.model;
public enum WorkflowStatus {
	NEWREQUEST, LOCALSHRINERAVALIATION, LOCALCOMMUNITYSOLUTION, REJECTNOTIFICATION,
	
	LOCALCLUBAVALIATION, LOCALCLUBSOLUTION, TEMPLEAVALIATION, TEMPLESOLUTION, INTERNATIONALSHRINERAVALIATION, INTERNATIONALSHRINERSOLUTION, INTERNATIONALSHRINERPARTNERFORWARD, INTERNATIONALSHRINERCLUBNOTIFICATION;
}